# Generated by Django 4.2 on 2023-12-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cinemahall_movietiming_seatreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietiming',
            name='timing',
            field=models.CharField(choices=[('06:00', '6:00'), ('09:00', '9:00'), ('12:00', '12:00'), ('15:00', '15:00'), ('18:00', '18:00'), ('21:00', '21:00')], max_length=5),
        ),
    ]
