# Generated by Django 4.2 on 2023-12-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movietiming_movie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movietiming',
            unique_together={('movie', 'timing')},
        ),
    ]
