# Generated by Django 4.2 on 2023-12-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_movietiming_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietiming',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
    ]
