# Generated by Django 4.2 on 2023-12-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_movietiming_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(choices=[('06:00', '6:00'), ('09:00', '9:00'), ('12:00', '12:00'), ('15:00', '15:00'), ('18:00', '18:00'), ('21:00', '21:00')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='movietiming',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='movietiming',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='movietiming',
            name='timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timings'),
        ),
        migrations.AlterUniqueTogether(
            name='movietiming',
            unique_together={('movie', 'timing')},
        ),
    ]
