# Generated by Django 4.2 on 2023-12-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_timings_timing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movietiming',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='movietiming',
            name='timing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.timings'),
        ),
    ]
