# Generated by Django 4.2 on 2023-12-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_movietiming_timing_alter_timings_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietiming',
            name='timing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.timings'),
        ),
    ]
