# Generated by Django 4.2 on 2023-12-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_movietiming_timing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movietiming',
            unique_together={('movie', 'timing', 'cinema_hall')},
        ),
    ]
