# Generated by Django 4.2 on 2023-12-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_movietiming_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietiming',
            name='timing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.timings'),
        ),
    ]
