# Generated by Django 4.2 on 2023-12-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_movietiming_timing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movietiming',
            unique_together={('timing', 'cinema_hall')},
        ),
    ]
