# Generated by Django 4.2 on 2023-12-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_movietiming_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('is_filled', models.BooleanField(default=False)),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cinemahall')),
            ],
        ),
        migrations.DeleteModel(
            name='SeatReservation',
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(check=models.Q(('seat_number__lte', 10)), name='max_10_seats'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('cinema_hall', 'seat_number')},
        ),
    ]
