# Generated by Django 4.2 on 2023-12-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seat_delete_seatreservation_seat_max_10_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='total_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
