# Generated by Django 4.2 on 2023-12-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cinemahall_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reservation_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
